name: Build and Push to Personal Registry

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE: ${{ secrets.REGISTRY_URL }}/dev-tools

    steps:
      - uses: actions/checkout@v6

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login \
            ${{ secrets.REGISTRY_URL }} \
            -u ${{ secrets.REGISTRY_USERNAME }} \
            --password-stdin

      - name: Build image
        run: docker build -t $IMAGE:${{ github.ref_name }} .

      - name: Push image
        run: docker push $IMAGE:${{ github.ref_name }}

      - name: Tag & push latest for release tags
        run: |
          docker tag $IMAGE:${{ github.ref_name }} $IMAGE:latest
          docker push $IMAGE:latest
